### ISSUE TITLE
not working in 1.21.4

### ISSUE THREAD

**Issue by unlikelyvee** [sniffercraft34/Bedrock-Bridging#1]
shows up in mod list but i cant find any settings or keybind for this

**Comment by sniffercraft34** [comment]
Yeah 1.21.4 has a few issues with data packs try /datapack enable then you will see the name and then it should work
If it doesn’t then you’ll have to wait for Minecraft to update
Also if you are using the mod then there are no key binds just toggle commands you can find on the project page on modrinth or planet minecraft 
Sorry about that =D
