### ISSUE TITLE
Not working 1.21.4

### ISSUE THREAD

**Issue by Kishku7** [sniffercraft34/Bedrock-Bridging#2]
I've installed the Datapack on the server (paper 1.21.4 build 12) and client 1.21.4.
I've issued the ON function on both the server console as well as in the client.

Not seeing the placement outline and not getting any bridging placement.

**Comment by sniffercraft34** [comment]
This is an issue with Minecraft 1.21.4.
You need to use /datapack enable then enable this one

**Comment by Grawl** [comment]
what is datapack

**Comment by sniffercraft34** [comment]
@Grawl a datapack is like a mod that you install on separate worlds and can only run commands, add structures, biomes, recipes etc.
